public static class EntityExtensionsGenerated
{
public static FinalGame.Develop.Gameplay.Entities.Entity AddMoveSpeed(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.MoveSpeed, new FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single>());
public static FinalGame.Develop.Gameplay.Entities.Entity AddMoveSpeed(this FinalGame.Develop.Gameplay.Entities.Entity entity, FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single> value) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.MoveSpeed, value);
public static FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single> GetMoveSpeed(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.GetValue<FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single>>(FinalGame.Develop.Gameplay.Entities.EntityValues.MoveSpeed);
public static System.Boolean TryGetMoveSpeed(this FinalGame.Develop.Gameplay.Entities.Entity entity, out FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single> value) => entity.TryGetValue<FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single>>(FinalGame.Develop.Gameplay.Entities.EntityValues.MoveSpeed, out value);
public static FinalGame.Develop.Gameplay.Entities.Entity AddMoveDirection(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.MoveDirection, new FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3>());
public static FinalGame.Develop.Gameplay.Entities.Entity AddMoveDirection(this FinalGame.Develop.Gameplay.Entities.Entity entity, FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3> value) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.MoveDirection, value);
public static FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3> GetMoveDirection(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.GetValue<FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3>>(FinalGame.Develop.Gameplay.Entities.EntityValues.MoveDirection);
public static System.Boolean TryGetMoveDirection(this FinalGame.Develop.Gameplay.Entities.Entity entity, out FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3> value) => entity.TryGetValue<FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3>>(FinalGame.Develop.Gameplay.Entities.EntityValues.MoveDirection, out value);
public static FinalGame.Develop.Gameplay.Entities.Entity AddRotationSpeed(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.RotationSpeed, new FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single>());
public static FinalGame.Develop.Gameplay.Entities.Entity AddRotationSpeed(this FinalGame.Develop.Gameplay.Entities.Entity entity, FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single> value) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.RotationSpeed, value);
public static FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single> GetRotationSpeed(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.GetValue<FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single>>(FinalGame.Develop.Gameplay.Entities.EntityValues.RotationSpeed);
public static System.Boolean TryGetRotationSpeed(this FinalGame.Develop.Gameplay.Entities.Entity entity, out FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single> value) => entity.TryGetValue<FinalGame.Develop.Utils.Reactive.ReactiveVariable<System.Single>>(FinalGame.Develop.Gameplay.Entities.EntityValues.RotationSpeed, out value);
public static FinalGame.Develop.Gameplay.Entities.Entity AddRotationDirection(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.RotationDirection, new FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3>());
public static FinalGame.Develop.Gameplay.Entities.Entity AddRotationDirection(this FinalGame.Develop.Gameplay.Entities.Entity entity, FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3> value) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.RotationDirection, value);
public static FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3> GetRotationDirection(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.GetValue<FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3>>(FinalGame.Develop.Gameplay.Entities.EntityValues.RotationDirection);
public static System.Boolean TryGetRotationDirection(this FinalGame.Develop.Gameplay.Entities.Entity entity, out FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3> value) => entity.TryGetValue<FinalGame.Develop.Utils.Reactive.ReactiveVariable<UnityEngine.Vector3>>(FinalGame.Develop.Gameplay.Entities.EntityValues.RotationDirection, out value);
public static FinalGame.Develop.Gameplay.Entities.Entity AddCharacterController(this FinalGame.Develop.Gameplay.Entities.Entity entity, UnityEngine.CharacterController value) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.CharacterController, value);
public static UnityEngine.CharacterController GetCharacterController(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.GetValue<UnityEngine.CharacterController>(FinalGame.Develop.Gameplay.Entities.EntityValues.CharacterController);
public static System.Boolean TryGetCharacterController(this FinalGame.Develop.Gameplay.Entities.Entity entity, out UnityEngine.CharacterController value) => entity.TryGetValue<UnityEngine.CharacterController>(FinalGame.Develop.Gameplay.Entities.EntityValues.CharacterController, out value);
public static FinalGame.Develop.Gameplay.Entities.Entity AddTransform(this FinalGame.Develop.Gameplay.Entities.Entity entity, UnityEngine.Transform value) => entity.AddValue(FinalGame.Develop.Gameplay.Entities.EntityValues.Transform, value);
public static UnityEngine.Transform GetTransform(this FinalGame.Develop.Gameplay.Entities.Entity entity) => entity.GetValue<UnityEngine.Transform>(FinalGame.Develop.Gameplay.Entities.EntityValues.Transform);
public static System.Boolean TryGetTransform(this FinalGame.Develop.Gameplay.Entities.Entity entity, out UnityEngine.Transform value) => entity.TryGetValue<UnityEngine.Transform>(FinalGame.Develop.Gameplay.Entities.EntityValues.Transform, out value);
}
